/*!
 * \addtogroup grp_libopenacc_api_internal Internal
 * @{
 * 
 * \file OpenACC/internal/compiler.h
 *
 * \author Tristan Vanderbruggen
 * \date 10/31/2013
 *
 */

#ifndef LIBOPENACC_INTERNAL_COMPILER
#define LIBOPENACC_INTERNAL_COMPILER 20131031

#ifdef __cplusplus
extern "C" {
#endif

typedef struct acc_region_desc_t_ * acc_region_desc_t;

/// Data-structure the compiler use to communicate information to the runtime
struct acc_compiler_data_t_ {
  const char * acc_runtime_dir;
  const char * acc_runtime_ocl;
  const char * acc_kernels_dir;
  const unsigned long num_regions;
  const acc_region_desc_t * regions;
};

typedef struct acc_compiler_data_t_ acc_compiler_data_t;

/*!
 * Forward declaration of compiler_data which will be generated by the compiler
 * Actual declaration is generated by the compiler.
 */
extern acc_compiler_data_t compiler_data;

#ifdef __cplusplus
}
#endif

#endif /* LIBOPENACC_INTERNAL_COMPILER */

/** @} */

