
all:
	make -C 002 all
	make -C 101 all
	make -C 102 all
	make -C 103 all
	make -C 109 all
	make -C 501 all
	make -C 509 all

check:
	make -C 101 check
	make -C 102 check
	make -C 103 check
	make -C 109 check

clean:
	make -C 002 clean
	make -C 101 clean
	make -C 102 clean
	make -C 103 clean
	make -C 109 clean
	make -C 501 clean
	make -C 509 clean

