
all:
	make -C 002 all
	make -C 003 all
	make -C 101 all
	make -C 102 all
	make -C 103 all
	make -C 109 all
	make -C 501 all
	make -C 509 all
	make -C X09-tunning all
	make -C tuner all

check:
	make -C 101 check
	make -C 102 check
	make -C 103 check
	make -C 109 check
	make -C X09-tunning check
	make -C tuner check

clean:
	make -C 002 clean
	make -C 003 clean
	make -C 101 clean
	make -C 102 clean
	make -C 103 clean
	make -C 109 clean
	make -C 501 clean
	make -C 509 clean
	make -C X09-tunning clean
	make -C tuner clean

