#include "OpenACC/internal/region.h" 
#include "OpenACC/internal/compiler.h" 
/* File generated by Driver<Model>::getFileID("host-data.c") */
struct acc_loop_t_ ;
struct acc_kernel_version_t_ ;
struct acc_compiler_data_t_ ;
size_t param_sizes_0x3087c70[3] = {sizeof(int ), sizeof(int ), sizeof(int )};
size_t scalar_sizes_0x3087c70[0] = {};
struct acc_loop_t_ loops_0x26cdd20[3UL] = {{{0L, 0L, 1L, 1L, 1L, 1L, 1L}}, {{0L, 1L, 1L, 0L, 1L, 1L, 1L}}, {{0L, 1L, 1L, 1L, 1L, 1L, 1L}}};
struct acc_kernel_version_t_ version_0 = {0, 0, 1, loops_0x26cdd20, "kernel_0x3087c70_0"};
struct acc_kernel_version_t_ *versions[1UL] = {&version_0};

unsigned portions[2] = {9,7};

const struct acc_loop_splitter_t_ kernel_0x00_splitted_loop = { 0, e_contiguous, 2, portions, 0 };

struct acc_kernel_desc_t_ kernel_desc_0_0 = {
  0,
  "",
  3, param_sizes_0x3087c70,
  0, scalar_sizes_0x3087c70,
  3,
  3,
  1, versions,
  &kernel_0x00_splitted_loop
};

struct acc_kernel_desc_t_ *kernels_0[1UL] = {&kernel_desc_0_0};

const struct {
  acc_device_t kind;
  size_t num;
} dev_list[2] = { {acc_device_nvidia, 0}, {acc_device_xeonphi, 0} };

const struct acc_data_distribution_t_ region_0x00_data_dist [2] = {
  { e_contiguous, 2, portions, 0 },
  { e_contiguous, 2, portions, 0 }
};

struct acc_region_desc_t_ region_desc_0 = {
  0,
  "kernels.cl",
  0, NULL,
  1, kernels_0,
  2, dev_list,
  2, region_0x00_data_dist
};


struct acc_region_desc_t_ *regions[1UL] = {&region_desc_0};

struct acc_compiler_data_t_ compiler_data = {LIBOPENACC_DIR, "lib/opencl/libopenacc.cl", KERNEL_DIR, 1, regions};
