/*!
 *  \file tests/acc_compiler_data.c
 *
 * This file provides default version of the code that should be generated by the compiler for the runtime.
 *
 */

#include "OpenACC/libopenacc-internal.h"

#ifndef ACC_RUNTIME_DIR
# error "Need OpenACC runtime directory."
#endif
#ifndef ACC_RUNTIME_OPENCL
# define ACC_RUNTIME_OPENCL "lib/libopenacc.cl"
#endif

struct acc_kernel_version_t_ kernel_0x00000000_default = {
  0, 0, 0, NULL, ""
};

struct { unsigned long strides[4]; } kernel_0x00000000_v1_tiling[1] = {
  (unsigned long [4]){1,1,0,1}
};

struct acc_kernel_version_t_ kernel_0x00000000_v1 = {
  0, 0, 1, kernel_0x00000000_v1_tiling, "_gang_worker_tile_2"
};

acc_kernel_version_t kernel_0x00000000_versions[2] = { &kernel_0x00000000_default , &kernel_0x00000000_v1 };

struct acc_kernel_desc_t_ kernel_0x00000000_desc = {
  0,
  "vect_add_kernel",
  0, NULL,
  3,
  1,
  2, kernel_0x00000000_versions
};

acc_kernel_desc_t region_0x00000000_kernels[1] = { &kernel_0x00000000_desc };

struct acc_region_desc_t_ region_0x00000000_desc = {
  0,
  "vectadd.cl",
  0, NULL,
  1, region_0x00000000_kernels
};

acc_region_desc_t regions[1] = { &region_0x00000000_desc };

acc_compiler_data_t compiler_data = {
  (const char * ) ACC_RUNTIME_DIR,    /* Absolute (or relative) directory for OpenACC runtime (needed to compile OpenCL C codes) */
  (const char * ) ACC_RUNTIME_OPENCL, /* Name of the OpenCL C runtime file */
  1, regions
};

