/*!
 *  \file tests/acc_compiler_data.c
 *
 * This file provides default version of the code that should be generated by the compiler for the runtime.
 *
 */

#include "OpenACC/internal/compiler.h"
#include "OpenACC/internal/region.h"
#include "OpenACC/internal/kernel.h"
#include "OpenACC/internal/loop.h"

#ifndef ACC_RUNTIME_DIR
# error "Need OpenACC runtime directory."
#endif
#ifndef ACC_RUNTIME_OPENCL
# define ACC_RUNTIME_OPENCL "lib/opencl/libopenacc.cl"
#endif

acc_compiler_data_t compiler_data = {
  (const char * ) ACC_RUNTIME_DIR,    /* Absolute (or relative) directory for OpenACC runtime (needed to compile OpenCL C codes) */
  (const char * ) ACC_RUNTIME_OPENCL, /* Name of the OpenCL C runtime file */
  0, NULL
};

