/*!
 * \file libopenacc-internal.h
 *
 * \author Tristan Vanderbruggen
 * \date 09/2013
 * 
 * This file exposes the internal OpenACC API. This API is specific to our implementation.
 * The implementation of some functions of this API are generated when compiling a specific OpenACC application.
 *
 */

#ifndef __LIB_OPENACC_INTERNAL_H__
#define __LIB_OPENACC_INTERNAL_H__

#include "OpenACC/libopenacc.h"

//#include "OpenACC/lib-openacc-host-to-device.h"
typedef struct acc_context_t_ * acc_context_t;

// Internal OpenACC API

/*! \func acc_create_context
 *
 *  Create the context associated to 'region' and 'kernel'
 *
 *  \param[region] pointer to a parallel region descriptor
 *  \param[kernel] pointer to a kernel descriptor
 *  \return a non-zero value if an error occured
 */
acc_context_t acc_create_context(acc_parallel_t region, acc_kernel_t kernel);

/*!
 *  This functiom is generated by the compiler and initialize 'acc_runtime'
 */
void acc_application_specific_init();

#endif /* __LIB_OPENACC_INTERNAL_H__ */

